# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Httplog < Formula
  desc "httplog is a command line tool that logs HTTP requests"
  homepage "https://github.com/jamescun/httplog"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jamescun/httplog/releases/download/1.0.3/httplog_1.0.3_darwin_arm64.tar.gz"
      sha256 "1d56ae2523f97fc1b2d05d8c4fda9cf8af6b1edf187bd99d8355173b02976195"

      def install
        bin.install "httplog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jamescun/httplog/releases/download/1.0.3/httplog_1.0.3_darwin_amd64.tar.gz"
      sha256 "151d7521a1dcea93fe5deefdf72de416269873728b07914479868198bb2c617f"

      def install
        bin.install "httplog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamescun/httplog/releases/download/1.0.3/httplog_1.0.3_linux_arm64.tar.gz"
      sha256 "2c7a275f57a52c8ecb4468d226383d9f2a83f53620ff7e7b4529f632c0b4a0b2"

      def install
        bin.install "httplog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jamescun/httplog/releases/download/1.0.3/httplog_1.0.3_linux_amd64.tar.gz"
      sha256 "468c45249a8995134a2a02f53aeb94ad19a2f49e2602188164f200b5e21bfa35"

      def install
        bin.install "httplog"
      end
    end
  end
end
