# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Httplog < Formula
  desc "httplog is a command line tool that logs HTTP requests"
  homepage "https://github.com/jamescun/httplog"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jamescun/httplog/releases/download/v1.0.0/httplog_1.0.0_darwin_arm64.tar.gz"
      sha256 "306856f7fc3ee0fec6bfa83dffd1b25ac4e1bfdfd4935141f5bcd70b6cb36663"

      def install
        bin.install "httplog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jamescun/httplog/releases/download/v1.0.0/httplog_1.0.0_darwin_amd64.tar.gz"
      sha256 "653b9faa7b2f5578e13bcbc82698722b6eb7a77ae189a8f6ce34004959dc4e7b"

      def install
        bin.install "httplog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamescun/httplog/releases/download/v1.0.0/httplog_1.0.0_linux_arm64.tar.gz"
      sha256 "23372d345a2686d01d4b947f3edc5004fc0e14865fd4c40e0b22924959ff46c2"

      def install
        bin.install "httplog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jamescun/httplog/releases/download/v1.0.0/httplog_1.0.0_linux_amd64.tar.gz"
      sha256 "c00a578670980b03ac2a820f81204427c29ca936c46efeb68afd65b1e3221bc1"

      def install
        bin.install "httplog"
      end
    end
  end
end
