# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwt < Formula
  desc "A utility to interact with JSON Web Tokens"
  homepage "https://github.com/jamescun/jwt"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jamescun/jwt/releases/download/v0.0.1/jwt_0.0.1_darwin_arm64.tar.gz"
      sha256 "0945cdfec45e9b7ac32f0877dfdaccbc8a32418dc42d1a5e77a555ec469c9520"

      def install
        bin.install "jwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jamescun/jwt/releases/download/v0.0.1/jwt_0.0.1_darwin_amd64.tar.gz"
      sha256 "c01476c7e79e0b53bdbaf97bf00131b51b3f8e7578308abbfc5be325d5737cd8"

      def install
        bin.install "jwt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamescun/jwt/releases/download/v0.0.1/jwt_0.0.1_linux_arm64.tar.gz"
      sha256 "f93bcc91b72fdd11702de3be29ada6b20a8dee2e8d6e66f005ac8d1646a592f9"

      def install
        bin.install "jwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jamescun/jwt/releases/download/v0.0.1/jwt_0.0.1_linux_amd64.tar.gz"
      sha256 "feeec73799cb87e67007511a542d3ca37c4f830dc5030e0874f89ebac9525751"

      def install
        bin.install "jwt"
      end
    end
  end
end
