# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yubca < Formula
  desc "Create and Operate a Certificate Authority from a YubiKey."
  homepage "https://github.com/jamescun/yubca"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jamescun/yubca/releases/download/v0.0.1/yubca_0.0.1_darwin_arm64.tar.gz"
      sha256 "2edcdfd9901d5f135c51f3b3c8800768ff7579f76f4b5f4793bfde78cbf836ea"

      def install
        bin.install "yubca"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jamescun/yubca/releases/download/v0.0.1/yubca_0.0.1_darwin_amd64.tar.gz"
      sha256 "7b0a8a6771b48ed3fd4bccad48c12d324f51b37b8cb59c4adb68488c6c0f0eb3"

      def install
        bin.install "yubca"
      end
    end
  end
end
